"use client";
import { useEffect, useMemo, useState } from "react";
import { EmptyState } from "@/components/ui/states";

export interface TableColumn<T> { key: string; label: string; render: (row: T) => React.ReactNode; }
<<<<<<< Updated upstream
export function DataTable<T>({ rows, columns, searchPlaceholder = "Search records...", getRowKey }: { rows: T[]; columns: TableColumn<T>[]; searchPlaceholder?: string; getRowKey: (row: T) => string }) {
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const pageSize = 6;
  const filtered = useMemo(() => rows.filter((row) => Object.values(row as Record<string, unknown>).some((value) => String(value ?? "").toLowerCase().includes(search.toLowerCase()))), [rows, search]);
  const pageRows = filtered.slice((page - 1) * pageSize, page * pageSize); const pages = Math.max(1, Math.ceil(filtered.length / pageSize));
  return <section className="overflow-hidden rounded-[24px] border border-line bg-surface backdrop-blur-card"><div className="flex flex-col gap-3 border-b border-line-faint p-4 sm:flex-row sm:items-center sm:justify-between"><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder={searchPlaceholder} className="w-full max-w-sm rounded-full border border-line bg-deep px-4 py-2.5 text-sm text-ink placeholder:text-ink-search"/><span className="text-xs text-ink-dim">{filtered.length} records</span></div>{pageRows.length === 0 ? <EmptyState className="m-4" title="No records found" message="Adjust the search or filters and try again." /> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-panel-head text-[10px] uppercase tracking-wider text-ink-dim"><tr>{columns.map((column) => <th className="whitespace-nowrap px-5 py-4" key={column.key}>{column.label}</th>)}</tr></thead><tbody>{pageRows.map((row) => <tr className="border-t border-line-faint hover:bg-white/[0.02]" key={getRowKey(row)}>{columns.map((column) => <td className="whitespace-nowrap px-5 py-4 text-ink-bright" key={column.key}>{column.render(row)}</td>)}</tr>)}</tbody></table></div><div className="space-y-3 p-4 md:hidden">{pageRows.map((row) => <article key={getRowKey(row)} className="rounded-2xl border border-line-faint bg-deep/50 p-4">{columns.map((column) => <div className="flex justify-between gap-5 border-b border-line-faint py-2 last:border-0" key={column.key}><span className="text-xs text-ink-dim">{column.label}</span><span className="text-right text-xs text-ink">{column.render(row)}</span></div>)}</article>)}</div></>}<div className="flex items-center justify-end gap-3 border-t border-line-faint p-4"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="text-xs text-ink-dim disabled:opacity-30">Previous</button><span className="text-xs text-ink">{page} / {pages}</span><button disabled={page === pages} onClick={() => setPage((value) => value + 1)} className="text-xs text-ink-dim disabled:opacity-30">Next</button></div></section>;
=======
export function DataTable<T>({ rows, columns, searchPlaceholder = "Search records...", getRowKey, search = "", onSearch, serverSide = false, total, hasNextPage = false, hasPreviousPage = false, onNextPage, onPreviousPage }: { rows: T[]; columns: TableColumn<T>[]; searchPlaceholder?: string; getRowKey: (row: T) => string; search?: string; onSearch?: (value: string) => void; serverSide?: boolean; total?: number; hasNextPage?: boolean; hasPreviousPage?: boolean; onNextPage?: () => void; onPreviousPage?: () => void }) {
  const [localSearch, setLocalSearch] = useState(search); const [localPage, setLocalPage] = useState(0); const effectiveSearch = onSearch ? search : localSearch;
  const filtered = useMemo(() => serverSide ? rows : rows.filter((row) => Object.values(row as Record<string, unknown>).some((value) => String(value ?? "").toLowerCase().includes(effectiveSearch.toLowerCase()))), [rows, effectiveSearch, serverSide]);
  const pageSize = 10;
  useEffect(() => { setLocalPage(0); }, [effectiveSearch, rows]);
  const pageRows = serverSide ? rows : filtered.slice(localPage * pageSize, (localPage + 1) * pageSize); const count = total ?? (serverSide ? rows.length : filtered.length);
  const localHasPrevious = localPage > 0;
  const localHasNext = (localPage + 1) * pageSize < filtered.length;
  return <section className="overflow-hidden rounded-[24px] border border-line bg-surface backdrop-blur-card"><div className="flex flex-col gap-3 border-b border-line-faint p-4 sm:flex-row sm:items-center sm:justify-between"><input value={effectiveSearch} onChange={(event) => { const value = event.target.value; setLocalSearch(value); onSearch?.(value); }} placeholder={searchPlaceholder} className="w-full max-w-sm rounded-full border border-line bg-deep px-4 py-2.5 text-sm text-ink placeholder:text-ink-placeholder"/><span className="text-xs text-ink-dim">{count} records</span></div>{pageRows.length === 0 ? <EmptyState className="m-4" title="No records found" message="Adjust the search or filters and try again." /> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-panel-head text-[10px] uppercase tracking-wider text-ink-dim"><tr>{columns.map((column) => <th className="whitespace-nowrap px-5 py-4" key={column.key}>{column.label}</th>)}</tr></thead><tbody>{pageRows.map((row) => <tr className="border-t border-line-faint hover:bg-white/[0.02]" key={getRowKey(row)}>{columns.map((column) => <td className="whitespace-nowrap px-5 py-4 text-ink-bright" key={column.key}>{column.render(row)}</td>)}</tr>)}</tbody></table></div><div className="space-y-3 p-4 md:hidden">{pageRows.map((row) => <article key={getRowKey(row)} className="rounded-2xl border border-line-faint bg-deep/50 p-4">{columns.map((column) => <div className="flex justify-between gap-5 border-b border-line-faint py-2 last:border-0" key={column.key}><span className="text-xs text-ink-dim">{column.label}</span><span className="text-right text-xs text-ink">{column.render(row)}</span></div>)}</article>)}</div></>}<div className="flex items-center justify-end gap-3 border-t border-line-faint p-4"><button disabled={serverSide ? !hasPreviousPage : !localHasPrevious} onClick={serverSide ? onPreviousPage : () => setLocalPage((page) => Math.max(0, page - 1))} className="min-h-[44px] px-2 text-xs text-ink-dim disabled:opacity-30">Previous</button>{serverSide ? <span className="text-xs text-ink">Server results</span> : <span className="text-xs text-ink">Page {localPage + 1}</span>}<button disabled={serverSide ? !hasNextPage : !localHasNext} onClick={serverSide ? onNextPage : () => setLocalPage((page) => page + 1)} className="min-h-[44px] px-2 text-xs text-ink-dim disabled:opacity-30">Next</button></div></section>;
>>>>>>> Stashed changes
}
