"use client";
import Link from "next/link";
import { useAsync } from "@/controllers/useAsync";
import { api } from "@/services/api";
import { WorkspacePage } from "./WorkspacePage";
import { ErrorState, LoadingState } from "@/components/ui/states";
import type { AdminUserSummary, AdminAuditRecord, AdminIntegrationEvent } from "@/models/admin";

const labels = { overview: ["Admin / Overview", "System Administration"], users: ["Admin / Identity", "User Management"], roles: ["Admin / Governance", "Roles"], system: ["Admin / System", "System Health"], audit: ["Admin / Governance", "Audit Logs"], events: ["Admin / Governance", "Integration Events"] } as const;
type Kind = keyof typeof labels;

export function AdminApiView({ kind }: { kind: Kind }) {
  const { state, run } = useAsync(async (): Promise<unknown> => kind === "overview" ? api.admin.overview() : kind === "users" ? api.admin.users({ limit: 50 }) : kind === "roles" ? api.admin.roles() : kind === "system" ? api.admin.health() : kind === "audit" ? api.admin.auditLogs({ limit: 50 }) : api.admin.events({ limit: 50 }), { immediate: [] });
  const [eyebrow, title] = labels[kind];
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow={eyebrow} title={title} description="Backend-owned administrative data."><LoadingState label={`Loading ${title}`} /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow={eyebrow} title={title} description="Backend-owned administrative data."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  if (kind === "overview") return <AdminOverviewView data={state.data as import("@/models/admin").AdminOverview} />;
  if (kind === "users") return <WorkspacePage eyebrow={eyebrow} title={title} description="Read-only identity and membership projections."><UserTable items={pageItems<AdminUser>(state.data)} /></WorkspacePage>;
  if (kind === "roles") return <WorkspacePage eyebrow={eyebrow} title={title} description="Canonical roles are read-only backend policy."><RoleView roles={arrayField<string>(state.data, "roles")} /></WorkspacePage>;
  if (kind === "system") return <WorkspacePage eyebrow={eyebrow} title={title} description="Only backend-reported health facts are shown."><HealthView data={state.data as unknown as import("@/models/admin").AdminHealth} /></WorkspacePage>;
  if (kind === "audit") return <WorkspacePage eyebrow={eyebrow} title={title} description="Redacted, read-only audit history."><AuditTable items={pageItems<AdminAuditRecord>(state.data)} /></WorkspacePage>;
  return <WorkspacePage eyebrow={eyebrow} title={title} description="Operational webhook metadata without provider payloads."><EventTable items={pageItems<AdminIntegrationEvent>(state.data)} /></WorkspacePage>;
}

export function AdminUserDetailView({ userId }: { userId: string }) { const { state, run } = useAsync(() => api.admin.user(userId), { immediate: [] }); if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Admin / Identity" title="User" description="Read-only identity detail."><LoadingState label="Loading user" /></WorkspacePage>; if (state.status === "error") return <WorkspacePage eyebrow="Admin / Identity" title="User" description="Read-only identity detail."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>; const memberships = Array.isArray(state.data.memberships) ? state.data.memberships : []; return <WorkspacePage eyebrow="Admin / Identity" title={state.data.fullName || state.data.email} description={state.data.email}><dl className="grid gap-3 rounded-2xl border border-line bg-surface p-5 text-sm sm:grid-cols-2"><Info label="Status" value={state.data.status} /><Info label="Type" value={state.data.userType} /><Info label="Last login" value={state.data.lastLoginAt ? new Date(state.data.lastLoginAt).toLocaleString() : "—"} /><Info label="User ID" value={state.data.userId} /></dl><section className="mt-5 rounded-2xl border border-line bg-surface p-5"><h2 className="font-semibold text-ink">Memberships</h2><div className="mt-3 space-y-2 text-sm">{memberships.map((membership) => <p key={`${membership.organizationId}-${membership.role}`} className="text-ink-dim">{membership.organizationId} · {membership.role} · {membership.status}</p>)}</div></section></WorkspacePage>; }

export function AdminAuditDetailView({ auditId }: { auditId: string }) { const { state, run } = useAsync(() => api.admin.auditLog(auditId), { immediate: [] }); if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Admin / Governance" title="Audit record" description="Redacted, read-only audit detail."><LoadingState label="Loading audit record" /></WorkspacePage>; if (state.status === "error") return <WorkspacePage eyebrow="Admin / Governance" title="Audit record" description="Redacted, read-only audit detail."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>; const record = state.data; return <WorkspacePage eyebrow="Admin / Governance" title={record.action} description="Redacted, read-only audit detail."><dl className="grid gap-3 rounded-2xl border border-line bg-surface p-5 text-sm sm:grid-cols-2"><Info label="Resource" value={`${record.resourceType} · ${record.resourceId}`} /><Info label="Actor" value={record.actorUserId ?? record.actorType} /><Info label="Organization" value={record.organizationId ?? "—"} /><Info label="Created" value={new Date(record.createdAt).toLocaleString()} /></dl><ChangeData label="Before" data={record.beforeData} /><ChangeData label="After" data={record.afterData} /></WorkspacePage>; }

export function AdminIntegrationEventDetailView({ eventId }: { eventId: string }) { const { state, run } = useAsync(() => api.admin.event(eventId), { immediate: [] }); if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Admin / Governance" title="Integration event" description="Safe webhook lifecycle metadata only."><LoadingState label="Loading integration event" /></WorkspacePage>; if (state.status === "error") return <WorkspacePage eyebrow="Admin / Governance" title="Integration event" description="Safe webhook lifecycle metadata only."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>; const event = state.data; return <WorkspacePage eyebrow="Admin / Governance" title={`${event.provider} · ${event.eventType}`} description="Safe lifecycle metadata; payloads, signatures, tokens and retry controls are never exposed."><dl className="grid gap-3 rounded-2xl border border-line bg-surface p-5 text-sm sm:grid-cols-2"><Info label="Status" value={event.status} /><Info label="Attempts" value={String(event.attemptCount)} /><Info label="External event ID" value={event.externalEventId} /><Info label="Retry exhausted" value={event.retryExhausted ? "yes" : "no"} /><Info label="Received" value={new Date(event.receivedAt).toLocaleString()} /><Info label="Last attempt" value={event.lastAttemptAt ? new Date(event.lastAttemptAt).toLocaleString() : "—"} /><Info label="Next attempt" value={event.nextAttemptAt ? new Date(event.nextAttemptAt).toLocaleString() : "—"} /><Info label="Processed" value={event.processedAt ? new Date(event.processedAt).toLocaleString() : "—"} /><Info label="Last error summary" value={event.lastErrorSummary ?? "—"} /></dl></WorkspacePage>; }

function AdminOverviewView({ data }: { data: { users: { countsByStatus: Record<string, number>; countsByType: Record<string, number> }; memberships: { countsByRole: Record<string, number>; countsByStatus: Record<string, number> }; governance: { webhookEventCountsByStatus: Record<string, number> }; ddConfiguration: { templateCount: number; versionCountsByStatus: Record<string, number> } } }) { return <WorkspacePage eyebrow="Admin / Overview" title="System Administration" description="Source-backed identity, governance and DD configuration state." stats={[{ label: "Users", value: String(Object.values(data.users.countsByStatus).reduce((a, b) => a + b, 0)) }, { label: "Memberships", value: String(Object.values(data.memberships.countsByStatus).reduce((a, b) => a + b, 0)) }, { label: "DD templates", value: String(data.ddConfiguration.templateCount) }, { label: "Webhook events", value: String(Object.values(data.governance.webhookEventCountsByStatus).reduce((a, b) => a + b, 0)) }]}><div className="grid gap-4 lg:grid-cols-3"><Metric title="Users by status" values={data.users.countsByStatus} /><Metric title="Memberships by role" values={data.memberships.countsByRole} /><Metric title="Webhook events" values={data.governance.webhookEventCountsByStatus} /></div></WorkspacePage>; }
<<<<<<< Updated upstream
function UserTable({ items }: { items: AdminUserSummary[] }) { return <div className="overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-line text-ink-dim"><th className="p-4">Identity</th><th className="p-4">Type</th><th className="p-4">Status</th></tr></thead><tbody>{items.map((user) => <tr key={user.userId} className="border-b border-line/60"><td className="p-4"><Link href={`/admin/users/${encodeURIComponent(user.userId)}`} className="font-medium text-accent hover:underline">{user.fullName || user.email}</Link><div className="text-xs text-ink-dim">{user.email}</div></td><td className="p-4">{user.userType}</td><td className="p-4">{user.status}</td></tr>)}</tbody></table>{items.length === 0 ? <p className="p-8 text-center text-sm text-ink-dim">No users returned.</p> : null}</div>; }
function AuditTable({ items }: { items: AdminAuditRecord[] }) { return <div className="overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-line text-ink-dim"><th className="p-4">Action</th><th className="p-4">Resource</th><th className="p-4">Actor</th><th className="p-4">Created</th></tr></thead><tbody>{items.map((item) => <tr key={item.auditId} className="border-b border-line/60"><td className="p-4"><Link href={`/admin/audit-logs/${encodeURIComponent(item.auditId)}`} className="font-medium text-accent hover:underline">{item.action}</Link></td><td className="p-4">{item.resourceType} · {item.resourceId}</td><td className="p-4">{item.actorUserId ?? item.actorType}</td><td className="p-4">{new Date(item.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{items.length === 0 ? <p className="p-8 text-center text-sm text-ink-dim">No audit records returned.</p> : null}</div>; }
function EventTable({ items }: { items: AdminIntegrationEvent[] }) { return <div className="overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-line text-ink-dim"><th className="p-4">Provider / type</th><th className="p-4">Status</th><th className="p-4">Attempts</th><th className="p-4">Received</th></tr></thead><tbody>{items.map((item) => <tr key={item.eventId} className="border-b border-line/60"><td className="p-4"><Link href={`/admin/integrations/events/${encodeURIComponent(item.eventId)}`} className="font-medium text-accent hover:underline">{item.provider} · {item.eventType}</Link></td><td className="p-4">{item.status}{item.retryExhausted ? " · retry exhausted" : ""}</td><td className="p-4">{item.attemptCount}</td><td className="p-4">{new Date(item.receivedAt).toLocaleString()}</td></tr>)}</tbody></table>{items.length === 0 ? <p className="p-8 text-center text-sm text-ink-dim">No integration events returned.</p> : null}</div>; }
=======
function pageItems<T>(value: unknown): T[] { if (Array.isArray(value)) return value as T[]; if (!value || typeof value !== "object") return []; const page = value as { items?: unknown; data?: { items?: unknown } }; if (Array.isArray(page.items)) return page.items as T[]; return Array.isArray(page.data?.items) ? page.data.items as T[] : []; }
function arrayField<T>(value: unknown, field: string): T[] { if (!value || typeof value !== "object") return []; const candidate = (value as Record<string, unknown>)[field]; return Array.isArray(candidate) ? candidate as T[] : []; }
function UserTable({ items }: { items?: AdminUser[] }) { const safeItems = Array.isArray(items) ? items : []; return <div className="overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-line text-ink-dim"><th className="p-4">Identity</th><th className="p-4">Type</th><th className="p-4">Status</th><th className="p-4">Memberships</th></tr></thead><tbody>{safeItems.map((user) => <tr key={user.userId} className="border-b border-line/60"><td className="p-4"><Link href={`/admin/users/${encodeURIComponent(user.userId)}`} className="font-medium text-accent hover:underline">{user.fullName || user.email}</Link><div className="text-xs text-ink-dim">{user.email}</div></td><td className="p-4">{user.userType}</td><td className="p-4">{user.status}</td><td className="p-4">{(Array.isArray(user.memberships) ? user.memberships : []).map((m) => `${m.role} (${m.status})`).join(", ") || "—"}</td></tr>)}</tbody></table>{safeItems.length === 0 ? <p className="p-8 text-center text-sm text-ink-dim">No users returned.</p> : null}</div>; }
function AuditTable({ items }: { items?: AdminAuditRecord[] }) { const safeItems = Array.isArray(items) ? items : []; return <div className="overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-line text-ink-dim"><th className="p-4">Action</th><th className="p-4">Resource</th><th className="p-4">Actor</th><th className="p-4">Created</th></tr></thead><tbody>{safeItems.map((item) => <tr key={item.auditId} className="border-b border-line/60"><td className="p-4"><Link href={`/admin/audit-logs/${encodeURIComponent(item.auditId)}`} className="font-medium text-accent hover:underline">{item.action}</Link></td><td className="p-4">{item.resourceType} · {item.resourceId}</td><td className="p-4">{item.actorUserId ?? item.actorType}</td><td className="p-4">{new Date(item.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{safeItems.length === 0 ? <p className="p-8 text-center text-sm text-ink-dim">No audit records returned.</p> : null}</div>; }
function EventTable({ items }: { items?: AdminIntegrationEvent[] }) { const safeItems = Array.isArray(items) ? items : []; return <div className="overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-line text-ink-dim"><th className="p-4">Provider / type</th><th className="p-4">Status</th><th className="p-4">Attempts</th><th className="p-4">Received</th></tr></thead><tbody>{safeItems.map((item) => <tr key={item.eventId} className="border-b border-line/60"><td className="p-4"><Link href={`/admin/integrations/events/${encodeURIComponent(item.eventId)}`} className="font-medium text-accent hover:underline">{item.provider} · {item.eventType}</Link></td><td className="p-4">{item.status}{item.retryExhausted ? " · retry exhausted" : ""}</td><td className="p-4">{item.attemptCount}</td><td className="p-4">{new Date(item.receivedAt).toLocaleString()}</td></tr>)}</tbody></table>{safeItems.length === 0 ? <p className="p-8 text-center text-sm text-ink-dim">No integration events returned.</p> : null}</div>; }
>>>>>>> Stashed changes
function ChangeData({ label, data }: { label: string; data: AdminAuditRecord["beforeData"] }) { return <section className="mt-5 rounded-2xl border border-line bg-surface p-5"><h2 className="font-semibold text-ink">{label}</h2>{data && Object.keys(data).length > 0 ? <dl className="mt-3 space-y-2 text-sm">{Object.entries(data).map(([key, value]) => <div key={key} className="flex justify-between gap-3"><dt className="text-ink-dim">{key}</dt><dd className="text-right text-ink">{String(value ?? "—")}</dd></div>)}</dl> : <p className="mt-3 text-sm text-ink-dim">No redacted {label.toLowerCase()} data returned.</p>}</section>; }
function RoleView({ roles }: { roles: string[] }) { return <div className="rounded-2xl border border-line bg-surface p-5"><ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{roles.map((role) => <li key={role} className="rounded-xl border border-line px-4 py-3 text-sm text-ink">{role}</li>)}</ul><p className="mt-4 text-xs text-ink-dim">Roles are canonical and read-only; this UI does not imply dynamic role administration.</p></div>; }
function HealthView({ data }: { data: { api: { status: string }; convex: { status: string; schemaVersion: number }; serverTime: string } }) { return <div className="grid gap-4 sm:grid-cols-3"><Metric title="API" values={{ status: data.api.status }} /><Metric title="Convex" values={{ status: data.convex.status, schemaVersion: data.convex.schemaVersion }} /><Metric title="Server time" values={{ time: new Date(data.serverTime).toLocaleString() }} /></div>; }
function Metric({ title, values }: { title: string; values: Record<string, string | number> }) { return <article className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-sm font-semibold text-ink">{title}</h2><dl className="mt-3 space-y-2 text-sm">{Object.entries(values).map(([key, value]) => <div key={key} className="flex justify-between gap-3"><dt className="text-ink-dim">{key}</dt><dd className="text-ink">{String(value)}</dd></div>)}</dl></article>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-wider text-ink-dim">{label}</dt><dd className="mt-1 text-ink">{value}</dd></div>; }
