"use client";
import Link from "next/link";
import { api } from "@/services/api";
import { useAsync } from "@/controllers/useAsync";
import { WorkspacePage } from "./WorkspacePage";
import { StatCard } from "@/components/shared/StatCard";
import { ErrorState, LoadingState } from "@/components/ui/states";

export function ManagerOverviewView() {
  const { state, run } = useAsync(() => api.manager.overview(), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / Overview" title="Business Operations" description="Source-backed commercial, team and project state."><LoadingState label="Loading manager overview" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / Overview" title="Business Operations" description="Source-backed commercial, team and project state."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  const data = state.data;
  const open = data.commercial.dealCounts.open ?? 0;
  const won = data.commercial.wonDealCount;
  const pending = data.projects.wonDealsPendingProject;
  return <WorkspacePage eyebrow="Manager / Overview" title="Business Operations" description="Source-backed commercial, team and project state." stats={[{ label: "Open Deals", value: String(open) }, { label: "Won Deals", value: String(won) }, { label: "Sales Team", value: String(data.team.activeSalesMemberCount) }, { label: "Pending Projects", value: String(pending) }]}><section className="mb-6 rounded-2xl border border-accent/25 bg-accent/[0.04] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-ink">Manager Handoff Queue</h2><p className="mt-1 text-xs text-ink-dim">Won deals awaiting readiness review or project conversion.</p></div><Link href="/manager/pipeline" className="rounded-full border border-accent/40 px-3 py-2 text-xs text-accent">Open pipeline</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-line bg-surface p-3"><p className="text-xs text-ink-dim">Won pending project</p><p className="mt-1 text-xl text-ink">{pending}</p></div><div className="rounded-xl border border-line bg-surface p-3"><p className="text-xs text-ink-dim">Readiness review</p><p className="mt-1 text-xl text-ink">Open per deal</p></div><div className="rounded-xl border border-line bg-surface p-3"><p className="text-xs text-ink-dim">Conversion</p><p className="mt-1 text-xl text-ink">Manager/Admin</p></div></div></section><section className="grid gap-4 lg:grid-cols-3">{["Commercial pipeline", "Projects by status", "Projects by vertical"].map((title, index) => <article key={title} className="rounded-[24px] border border-line bg-surface p-6"><h2 className="text-sm font-semibold text-ink">{title}</h2><pre className="mt-4 overflow-auto text-xs text-ink-dim">{JSON.stringify(index === 0 ? data.commercial.pipelineValueByCurrency : index === 1 ? data.projects.countsByStatus : data.projects.countsByVertical, null, 2)}</pre></article>)}</section></WorkspacePage>;
}

export function ManagerTeamView() {
  const { state, run } = useAsync(() => api.manager.team(), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / People" title="Team Performance" description="Active Sales memberships and source-backed metrics."><LoadingState label="Loading manager team" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / People" title="Team Performance" description="Active Sales memberships and source-backed metrics."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  return <WorkspacePage eyebrow="Manager / People" title="Team Performance" description="Active Sales memberships and source-backed metrics."><div className="overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-line text-ink-dim"><th className="p-4">Salesperson</th><th className="p-4">Assigned</th><th className="p-4">Won</th><th className="p-4">Pipeline</th><th className="p-4">Last activity</th></tr></thead><tbody>{state.data.items.map((member) => <tr key={member.userId} className="border-b border-line/60"><td className="p-4"><div className="font-medium text-ink">{member.fullName || "—"}</div><div className="text-xs text-ink-dim">{member.email}</div></td><td className="p-4">{member.dealCounts.assigned ?? 0}</td><td className="p-4">{member.dealCounts.won ?? 0}</td><td className="p-4">{member.pipelineValue.map((value) => `${value.currency} ${value.amountMinor}`).join(", ") || "—"}</td><td className="p-4">{member.lastActivityAt ? new Date(member.lastActivityAt).toLocaleString() : "—"}</td></tr>)}</tbody></table>{state.data.items.length === 0 ? <p className="p-8 text-center text-sm text-ink-dim">No active Sales members found.</p> : null}</div></WorkspacePage>;
}

export function ManagerReportsView() {
  const { state, run } = useAsync(() => api.manager.projectReport(), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / Analytics" title="Reports" description="Project reporting supplied by the backend."><LoadingState label="Loading manager reports" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / Analytics" title="Reports" description="Project reporting supplied by the backend."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  return <WorkspacePage eyebrow="Manager / Analytics" title="Reports" description="Project reporting supplied by the backend."><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Started projects", state.data.startedProjects], ["Completed projects", state.data.completedProjects], ["Won pending project", state.data.wonDealsPendingProject], ["Status buckets", Object.keys(state.data.countsByStatus).length]].map(([label, value]) => <StatCard key={String(label)} label={String(label)} value={String(value)} />)}</section></WorkspacePage>;
}

export function ManagerSalesPerformanceView() {
  const { state, run } = useAsync(() => Promise.all([api.salesWorkspace.overview(), api.salesWorkspace.conversionReport(), api.salesWorkspace.activityReport(), api.salesWorkspace.forecastReport()]), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / Commercial" title="Sales Performance" description="Backend sales overview and reports."><LoadingState label="Loading sales performance" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / Commercial" title="Sales Performance" description="Backend sales overview and reports."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  const [overview, conversion, activity, forecast] = state.data;
  return <WorkspacePage eyebrow="Manager / Commercial" title="Sales Performance" description="Source-backed pipeline, conversion, activity and forecast signals." stats={[{ label: "Open deals", value: String(overview.dealSummary.open) }, { label: "Won deals", value: String(overview.dealSummary.won) }, { label: "Total leads", value: String(conversion.totalLeads) }, { label: "Activities", value: String(activity.totalActivities) }]}><div className="grid gap-4 lg:grid-cols-3"><article className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-sm font-semibold text-ink">Pipeline by currency</h2><pre className="mt-3 overflow-auto text-xs text-ink-dim">{JSON.stringify(overview.pipelineValue, null, 2)}</pre></article><article className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-sm font-semibold text-ink">Conversion</h2><pre className="mt-3 overflow-auto text-xs text-ink-dim">{JSON.stringify(conversion.countsByStatus, null, 2)}</pre></article><article className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-sm font-semibold text-ink">Forecast</h2><pre className="mt-3 overflow-auto text-xs text-ink-dim">{JSON.stringify(forecast.byCurrency, null, 2)}</pre></article></div></WorkspacePage>;
}