"use client";
import Link from "next/link";
import { useAsync } from "@/controllers/useAsync";
import { api } from "@/services/api";
import type { ManagerProject, ManagerProjectStatus } from "@/models/manager";
import { formatMinorUnits } from "@/models/common";
import { WorkspacePage } from "./WorkspacePage";
import { GapNotice } from "./GapNotice";
import { ErrorState, LoadingState } from "@/components/ui/states";

const statusLabels: Record<ManagerProjectStatus, string> = { initiated: "Initiated", active: "Active", on_hold: "On hold", completed: "Completed", cancelled: "Cancelled" };
type Money = { currency: string; amountMinor: string };

export function ManagerOverviewView() {
  const { state, run } = useAsync(() => api.manager.overview(), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / Overview" title="Business Operations" description="Source-backed commercial, team and project state."><LoadingState label="Loading manager overview" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / Overview" title="Business Operations" description="Source-backed commercial, team and project state."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  const data = state.data;
  return <WorkspacePage eyebrow="Manager / Overview" title="Business Operations" description="Source-backed commercial, team and project state." stats={[{ label: "Open deals", value: String(data.commercial.dealCounts.open ?? 0) }, { label: "Won deals", value: String(data.commercial.wonDealCount) }, { label: "Active Sales", value: String(data.team.activeSalesMemberCount) }, { label: "Won pending project", value: String(data.projects.wonDealsPendingProject) }]}><div className="grid gap-4 lg:grid-cols-3"><MetricCard title="Commercial pipeline"><MoneyList values={data.commercial.pipelineValueByCurrency} /></MetricCard><MetricCard title="Projects by status"><CountList values={data.projects.countsByStatus} labelMap={statusLabels} /></MetricCard><MetricCard title="Projects by vertical"><CountList values={data.projects.countsByVertical} /></MetricCard></div><p className="mt-5 text-xs text-ink-dim">Revenue, GPU utilization and open-request totals are not part of the authoritative Manager contract.</p></WorkspacePage>;
}

export function ManagerTeamView() {
  const { state, run } = useAsync(() => api.manager.team(), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / People" title="Team Performance" description="Active Sales memberships and source-backed metrics."><LoadingState label="Loading manager team" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / People" title="Team Performance" description="Active Sales memberships and source-backed metrics."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  return <WorkspacePage eyebrow="Manager / People" title="Team Performance" description="Active Sales memberships and source-backed metrics."><TeamTable items={state.data.items} /></WorkspacePage>;
}

export function ManagerTeamMemberView({ userId }: { userId: string }) {
  const { state, run } = useAsync(() => api.manager.teamMember(userId), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / People" title="Team member" description="Source-backed member detail."><LoadingState label="Loading team member" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / People" title="Team member" description="Source-backed member detail."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  if (!state.data) return <WorkspacePage eyebrow="Manager / People" title="Team member" description="Source-backed member detail."><p className="text-sm text-ink-dim">Team member not found.</p></WorkspacePage>;
  return <WorkspacePage eyebrow="Manager / People" title={state.data.fullName || "Team member"} description={state.data.email} stats={[{ label: "Assigned", value: String(state.data.dealCounts.assigned) }, { label: "Won", value: String(state.data.dealCounts.won) }, { label: "Open", value: String(state.data.dealCounts.open) }, { label: "Activities", value: String(state.data.recentActivityCount ?? 0) }]}><MetricCard title="Pipeline by currency"><MoneyList values={state.data.pipelineValue} /></MetricCard><p className="mt-4 text-xs text-ink-dim">No lead conversion rate, quota attainment or subjective performance grade is returned by the backend.</p></WorkspacePage>;
}

export function ManagerProjectsView() {
  const { state, run } = useAsync(() => api.manager.projects({ limit: 50 }), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / Operations" title="Projects" description="Persisted project execution state."><LoadingState label="Loading projects" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / Operations" title="Projects" description="Persisted project execution state."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  return <WorkspacePage eyebrow="Manager / Operations" title="Projects" description="Persisted project execution state."><ProjectTable projects={state.data.items} /><GapNotice tone="blocked" title="Unmodeled operations remain unavailable" source="Manager Workspace Phase 1 handoff"><p>GPU capacity, deployments, infrastructure requests, land assessments, investment settlement and RFP lifecycle have no authoritative backend stores.</p></GapNotice></WorkspacePage>;
}

export function ManagerProjectDetailView({ projectId }: { projectId: string }) {
  const { state, run } = useAsync(() => api.manager.project(projectId), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / Operations" title="Project" description="Persisted project detail."><LoadingState label="Loading project" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / Operations" title="Project" description="Persisted project detail."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  const project = state.data;
  return <WorkspacePage eyebrow="Manager / Operations" title={project.name} description={`${project.projectCode} · ${project.vertical}`} stats={[{ label: "Status", value: statusLabels[project.status] }, { label: "Revision", value: String(project.revision) }]}><dl className="grid gap-3 rounded-2xl border border-line bg-surface p-5 text-sm sm:grid-cols-2"><Info label="Owner" value={project.ownerId ?? "Unassigned"} /><Info label="Started" value={project.startedAt ? new Date(project.startedAt).toLocaleDateString() : "—"} /><Info label="Updated" value={new Date(project.updatedAt).toLocaleString()} /><Info label="Source deal" value={project.sourceDeal.title} /></dl><section className="mt-5 rounded-2xl border border-line bg-surface p-5"><h2 className="font-semibold text-ink">Source deal</h2><p className="mt-2 text-sm text-ink-dim">{project.sourceDeal.title} · {project.sourceDeal.status}</p><p className="mt-1 text-sm text-ink">{formatMinorUnits(project.sourceDeal.estimatedValueMinor, project.sourceDeal.currency)}</p></section></WorkspacePage>;
}

export function ManagerReportsView() {
  const { state, run } = useAsync(() => api.manager.projectReport(), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / Analytics" title="Reports" description="Project reporting supplied by the backend."><LoadingState label="Loading manager reports" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / Analytics" title="Reports" description="Project reporting supplied by the backend."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  return <WorkspacePage eyebrow="Manager / Analytics" title="Reports" description="Project reporting supplied by the backend." stats={[{ label: "Started projects", value: String(state.data.startedProjects) }, { label: "Completed projects", value: String(state.data.completedProjects) }, { label: "Won pending project", value: String(state.data.wonDealsPendingProject) }]}><div className="grid gap-4 lg:grid-cols-2"><MetricCard title="Status counts"><CountList values={state.data.countsByStatus} labelMap={statusLabels} /></MetricCard><MetricCard title="Vertical counts"><CountList values={state.data.countsByVertical} /></MetricCard></div><p className="mt-5 text-xs text-ink-dim">Reports do not recognize revenue or merge money across currencies.</p></WorkspacePage>;
}

export function ManagerSalesPerformanceView() {
  const { state, run } = useAsync(() => Promise.all([api.salesWorkspace.overview(), api.salesWorkspace.conversionReport(), api.salesWorkspace.activityReport(), api.salesWorkspace.forecastReport()]), { immediate: [] });
  if (state.status === "loading" || state.status === "idle") return <WorkspacePage eyebrow="Manager / Commercial" title="Sales Performance" description="Backend sales overview and reports."><LoadingState label="Loading sales performance" /></WorkspacePage>;
  if (state.status === "error") return <WorkspacePage eyebrow="Manager / Commercial" title="Sales Performance" description="Backend sales overview and reports."><ErrorState error={state.error} onRetry={() => void run()} /></WorkspacePage>;
  const [overview, conversion, activity, forecast] = state.data;
  return <WorkspacePage eyebrow="Manager / Commercial" title="Sales Performance" description="Source-backed pipeline, conversion, activity and forecast signals." stats={[{ label: "Open deals", value: String(overview.dealSummary.open) }, { label: "Won deals", value: String(overview.dealSummary.won) }, { label: "Total leads", value: String(conversion.totalLeads) }, { label: "Activities", value: String(activity.totalActivities) }]}><div className="grid gap-4 lg:grid-cols-3"><MetricCard title="Pipeline by currency"><MoneyList values={overview.pipelineValue} /></MetricCard><MetricCard title="Conversion status"><CountList values={conversion.countsByStatus} /></MetricCard><MetricCard title="Forecast by currency"><dl className="space-y-2 text-sm">{Object.entries(forecast.byCurrency).map(([currency, bucket]) => <div key={currency} className="flex justify-between gap-3"><dt className="text-ink-dim">{currency}</dt><dd className="text-ink">{formatMinorUnits(bucket.totalPipeline, currency)}</dd></div>)}</dl></MetricCard></div><p className="mt-5 text-xs text-ink-dim">Lead ownership, conversion formulas and weighted forecast semantics remain product-policy questions; values are displayed as returned.</p></WorkspacePage>;
}

function TeamTable({ items }: { items: { userId: string; fullName: string; email: string; dealCounts: Record<string, number>; pipelineValue: Money[]; lastActivityAt: string | null }[] }) { return <div className="overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-line text-ink-dim"><th className="p-4">Salesperson</th><th className="p-4">Assigned</th><th className="p-4">Open</th><th className="p-4">Won</th><th className="p-4">Pipeline</th><th className="p-4">Last activity</th></tr></thead><tbody>{items.map((member) => <tr key={member.userId} className="border-b border-line/60"><td className="p-4"><Link href={`/manager/team/${encodeURIComponent(member.userId)}`} className="font-medium text-accent hover:underline">{member.fullName || "—"}</Link><div className="text-xs text-ink-dim">{member.email}</div></td><td className="p-4">{member.dealCounts.assigned}</td><td className="p-4">{member.dealCounts.open}</td><td className="p-4">{member.dealCounts.won}</td><td className="p-4"><MoneyList values={member.pipelineValue} /></td><td className="p-4">{member.lastActivityAt ? new Date(member.lastActivityAt).toLocaleString() : "—"}</td></tr>)}</tbody></table>{items.length === 0 ? <p className="p-8 text-center text-sm text-ink-dim">No active Sales members found.</p> : null}</div>; }
function ProjectTable({ projects }: { projects: ManagerProject[] }) { return <div className="mb-6 overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-line text-ink-dim"><th className="p-4">Project</th><th className="p-4">Vertical</th><th className="p-4">Status</th><th className="p-4">Source deal</th><th className="p-4">Updated</th></tr></thead><tbody>{projects.map((project) => <tr key={project.projectId} className="border-b border-line/60"><td className="p-4"><Link href={`/manager/operations/${encodeURIComponent(project.projectId)}`} className="font-medium text-accent hover:underline">{project.name}</Link><div className="text-xs text-ink-dim">{project.projectCode}</div></td><td className="p-4">{project.vertical}</td><td className="p-4">{statusLabels[project.status]}</td><td className="p-4">{project.sourceDeal.title}</td><td className="p-4">{new Date(project.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table>{projects.length === 0 ? <p className="p-8 text-center text-sm text-ink-dim">No projects returned.</p> : null}</div>; }
function MetricCard({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-sm font-semibold text-ink">{title}</h2><div className="mt-4">{children}</div></article>; }
function MoneyList({ values }: { values: Money[] }) { return values.length ? <ul className="space-y-2 text-sm text-ink">{values.map((value) => <li key={value.currency} className="flex justify-between gap-3"><span>{value.currency}</span><span>{formatMinorUnits(value.amountMinor, value.currency)}</span></li>)}</ul> : <p className="text-sm text-ink-dim">No values.</p>; }
function CountList({ values, labelMap = {} }: { values: Record<string, number>; labelMap?: Record<string, string> }) { const entries = Object.entries(values); return entries.length ? <ul className="space-y-2 text-sm text-ink">{entries.map(([key, value]) => <li key={key} className="flex justify-between gap-3"><span>{labelMap[key] ?? key}</span><span>{value}</span></li>)}</ul> : <p className="text-sm text-ink-dim">No records.</p>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-wider text-ink-dim">{label}</dt><dd className="mt-1 text-ink">{value}</dd></div>; }
