export type ManagerMoneyBucket = { currency: string; amountMinor: string };
export type ManagerOverview = { commercial: { dealCounts: Record<string, number>; pipelineValueByCurrency: ManagerMoneyBucket[]; wonDealCount: number }; team: { activeSalesMemberCount: number }; projects: { countsByStatus: Record<string, number>; countsByVertical: Record<string, number>; wonDealsPendingProject: number } };
export type ManagerTeamMember = { userId: string; fullName: string; email: string; userStatus: string; dealCounts: Record<string, number>; pipelineValue: ManagerMoneyBucket[]; recentActivityCount?: number; lastActivityAt: string | null };
export type ManagerTeamResponse = { items: ManagerTeamMember[] };
export type ManagerProjectReport = { countsByStatus: Record<string, number>; countsByVertical: Record<string, number>; startedProjects: number; completedProjects: number; wonDealsPendingProject: number };
export type ManagerProject = Record<string, unknown> & { projectId: string };
export type ManagerProjectListResponse = { items: ManagerProject[]; continueCursor?: string | null; isDone?: boolean };
export type ManagerProjectConversionRequest = { expectedRevision: number; idempotencyKey: string; projectCode: string; projectName?: string };
export type ManagerProjectConversionResponse = { projectId?: string; dealId?: string; created?: boolean } & Record<string, unknown>;
export type AssessmentLeadAssignmentStatus = "manager_review" | "assigned";
export type AssessmentLeadQueueItem = {
  leadId: string;
  assessmentSessionId: string | null;
  paymentId: string | null;
  dealId: string | null;
  source: string;
  vertical: string | null;
  persona: string | null;
  status: string;
  priority: string;
  summary: string | null;
  assignmentStatus: AssessmentLeadAssignmentStatus | null;
  assignedSalesUserId: string | null;
  assignedAt: number | null;
  sourcePayload: Record<string, unknown> | null;
  createdAt: string | null;
};
export type AssessmentLeadQueueResponse = { leads: AssessmentLeadQueueItem[] };
export type AssessmentLeadAssignmentResponse = {
  leadId: string;
  assignmentStatus: AssessmentLeadAssignmentStatus;
  assignedSalesUserId: string;
  assignedAt: number;
};
