"use client";
import { useState } from "react";
import type { DocumentFinalizeResponse, DocumentRetentionClass, DocumentUploadContextType } from "@/models/documents";
import { api, normalizeError } from "@/services/api";
async function sha256(file: File): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); return Array.from(new Uint8Array(digest)).map((value) => value.toString(16).padStart(2, "0")).join(""); }
export function SecureDocumentUpload({ contextType, resourceId, retentionClass, onFinalized }: { contextType: DocumentUploadContextType; resourceId: string; retentionClass: DocumentRetentionClass; onFinalized?: (result: DocumentFinalizeResponse) => void }) {
  const [file, setFile] = useState<File | null>(null); const [phase, setPhase] = useState<"idle" | "hashing" | "authorizing" | "uploading" | "finalizing" | "complete">("idle"); const [result, setResult] = useState<DocumentFinalizeResponse | null>(null); const [error, setError] = useState<string | null>(null);
  async function upload() { if (!file) return; setError(null); setResult(null); try { setPhase("hashing"); const checksum = await sha256(file); setPhase("authorizing"); const session = await api.documents.createUploadSession({ context: { type: contextType, resourceId }, originalFilename: file.name, mimeType: file.type || "application/octet-stream", sizeBytes: file.size, sha256Checksum: checksum, retentionClass, idempotencyKey: crypto.randomUUID() }); setPhase("uploading"); await api.documents.uploadToSignedUrl(session.uploadUrl, file, session.requiredHeaders); setPhase("finalizing"); const finalized = await api.documents.finalize(session.documentId); setResult(finalized); setPhase("complete"); onFinalized?.(finalized); } catch (cause) { setError(normalizeError(cause).message); setPhase("idle"); } }
  const phaseLabel = { idle: "Upload document", hashing: "Checking file…", authorizing: "Creating secure session…", uploading: "Uploading securely…", finalizing: "Finalizing…", complete: "Upload complete" } as const;
  return <section className="rounded-[24px] border border-line bg-surface p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-ink">Secure document upload</h2><p className="mt-1 text-xs leading-5 text-ink-dim">The browser uploads directly to private storage using a short-lived signed URL. Storage paths and credentials remain server-owned.</p></div><span className="rounded-full border border-line px-3 py-1 text-[10px] uppercase tracking-wider text-ink-dim">{retentionClass}</span></div><label className="mt-5 block rounded-2xl border border-dashed border-accent/35 bg-accent/[0.04] p-5 text-center"><input type="file" className="sr-only" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setResult(null); setError(null); setPhase("idle"); }} /><span className="text-sm font-medium text-ink">{file ? file.name : "Choose a document"}</span><span className="mt-1 block text-xs text-ink-dim">{file ? `${(file.size / 1024 / 1024).toFixed(2)} MB · ${file.type || "Unknown MIME"}` : "The checksum is calculated locally before authorization."}</span></label><button type="button" disabled={!file || !["idle", "complete"].includes(phase)} onClick={() => void upload()} className="mt-4 rounded-full bg-accent px-5 py-2.5 text-xs font-bold uppercase tracking-wider text-accent-fg disabled:opacity-40">{phaseLabel[phase]}</button>{error ? <p role="alert" className="mt-3 text-xs text-red-300">{error}</p> : null}{result ? <div className="mt-4 rounded-xl border border-line bg-white/[0.02] p-4 text-xs text-ink-dim"><p className="font-medium text-ink">Document registered successfully</p><p className="mt-2">Malware scan: {result.malwareScanStatus} · Encryption: {result.encryptionStatus}</p><p className="mt-1">Attachment becomes available only when backend policy accepts these states.</p></div> : null}</section>;
}
