"use client";

import { useEffect, useState } from "react";
import { WorkspacePage } from "@/components/workspace/WorkspacePage";
import { formatMinorUnits, type NormalizedError } from "@/models/common";
import type { SalesActivityReport, SalesConversionReport, SalesForecastReport } from "@/models/salesWorkspace";
import { api, normalizeError } from "@/services/api";

export function SalesReportsPage() {
  const [data, setData] = useState<{ conversion: SalesConversionReport; activity: SalesActivityReport; forecast: SalesForecastReport } | null>(null);
  const [error, setError] = useState<NormalizedError | null>(null);
  useEffect(() => { let active = true; Promise.all([api.salesWorkspace.conversionReport({ groupBy: "month" }), api.salesWorkspace.activityReport(), api.salesWorkspace.forecastReport()]).then(([conversion, activity, forecast]) => active && setData({ conversion, activity, forecast })).catch((cause) => active && setError(normalizeError(cause))); return () => { active = false; }; }, []);
  if (error) return <WorkspacePage eyebrow="Sales / Reports" title="Reports" description="On-demand reporting could not be loaded."><p role="alert" className="text-red-300">{error.message}{error.correlationId ? ` Support id: ${error.correlationId}` : ""}</p></WorkspacePage>;
  if (!data) return <WorkspacePage eyebrow="Sales / Reports" title="Reports" description="Loading conversion, activity, and forecast reports…" />;
  return <WorkspacePage eyebrow="Sales / Reports" title="Reports" description="On-demand source-backed report components. Conversion and weighted forecast formulas remain open policy, so the raw backend notes are shown."><div className="grid gap-6 lg:grid-cols-3"><section className="surface-card p-6"><p className="text-xs uppercase text-ink-dim">Total leads</p><p className="mt-2 text-3xl text-ink">{data.conversion.totalLeads}</p><p className="mt-2 text-xs text-ink-dim">{data.conversion._open.note}</p><div className="mt-4 space-y-1 text-sm text-ink-dim">{Object.entries(data.conversion.countsByStatus).map(([status, count]) => <p key={status}>{status}: {count}</p>)}</div></section><section className="surface-card p-6"><p className="text-xs uppercase text-ink-dim">Activity</p><p className="mt-2 text-3xl text-ink">{data.activity.totalActivities}</p><p className="mt-2 text-xs text-ink-dim">Overdue follow-ups: {data.activity.followUp.overdue}</p><div className="mt-4 space-y-1 text-sm text-ink-dim">{Object.entries(data.activity.countsByType).map(([type, count]) => <p key={type}>{type}: {count}</p>)}</div></section><section className="surface-card p-6"><p className="text-xs uppercase text-ink-dim">Forecast by currency</p><p className="mt-2 text-xs text-ink-dim">{data.forecast._open.note}</p><div className="mt-4 space-y-3">{Object.entries(data.forecast.byCurrency).length ? Object.entries(data.forecast.byCurrency).map(([currency, bucket]) => <div key={currency} className="border-b border-white/10 pb-2 text-sm"><p className="text-ink">{currency} · {bucket.dealCount} deals</p><p className="text-ink-dim">Pipeline {formatMinorUnits(bucket.totalPipeline, currency)}</p><p className="text-ink-dim">Weighted {formatMinorUnits(bucket.weightedPipeline, currency)}</p></div>) : <p className="text-sm text-ink-dim">No forecast data in the current scope.</p>}</div></section></div></WorkspacePage>;
}
