"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { WorkspacePage } from "@/components/workspace/WorkspacePage";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { Input, Select } from "@/components/ui/Field";
import { useAuth } from "@/controllers/AuthContext";
import { hasPermission } from "@/config/access";
import { api, normalizeError } from "@/services/api";
import type { Submission, SubmissionPriority, SubmissionVertical } from "@/models";
import type { NormalizedError } from "@/models/common";
export function SubmissionDetail({ id }: { id:string }) {
 const {profile}=useAuth(); const canConvert=hasPermission(profile,"lead:update"); const [item,setItem]=useState<Submission|null>(null); const [error,setError]=useState<NormalizedError|null>(null); const [loading,setLoading]=useState(true); const [organizationId,setOrganizationId]=useState(""); const [ownerId,setOwnerId]=useState(""); const [title,setTitle]=useState(""); const [vertical,setVertical]=useState<SubmissionVertical>("land"); const [priority,setPriority]=useState<SubmissionPriority>("normal"); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{setItem(await api.submissions.get(id));}catch(cause){setError(normalizeError(cause));}finally{setLoading(false);}},[id]); useEffect(()=>{void load();},[load]);
 async function convert(e:React.FormEvent){e.preventDefault();setMessage(null);if(!organizationId.trim()||!ownerId.trim()||!title.trim()){setMessage("Organization, owner and title are required.");return;}setSaving(true);try{await api.submissions.convert(id,{organizationId:organizationId.trim(),ownerId:ownerId.trim(),title:title.trim(),vertical,priority});setMessage("Submission converted to a deal.");await load();}catch(cause){setMessage(normalizeError(cause).message);}finally{setSaving(false);}}
 if(loading)return <LoadingState label="Loading submission"/>; if(error)return <ErrorState error={error} onRetry={()=>void load()}/>; if(!item)return null;
 return <WorkspacePage eyebrow="Sales / Submission" title={item.summary||"Submission detail"} description={item.source+" · "+(item.vertical||"unclassified")}><Link href="/sales/leads" className="text-xs font-bold uppercase tracking-wider text-accent hover:underline">← All submissions</Link><section className="mt-6 rounded-[24px] border border-line bg-surface p-6"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-ink-faint">Status</dt><dd className="mt-1 text-ink">{item.status}</dd></div><div><dt className="text-xs text-ink-faint">Lead id</dt><dd className="mt-1 font-mono text-ink">{item.leadId}</dd></div><div><dt className="text-xs text-ink-faint">Updated</dt><dd className="mt-1 text-ink">{new Date(item.updatedAt).toLocaleString()}</dd></div></dl></section>{canConvert&&item.status!=="converted"?<form onSubmit={convert} className="mt-6 rounded-[24px] border border-line bg-surface p-6"><h2 className="text-sm font-semibold text-ink">Convert to deal</h2><p className="mt-1 text-xs text-ink-dim">The backend performs the transactional lead/deal conversion.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Organization id *" value={organizationId} onChange={(e)=>setOrganizationId(e.target.value)}/><Input label="Owner id *" value={ownerId} onChange={(e)=>setOwnerId(e.target.value)}/><Input label="Deal title *" value={title} onChange={(e)=>setTitle(e.target.value)}/><Select label="Vertical *" value={vertical} onChange={(e)=>setVertical(e.target.value as SubmissionVertical)} options={["land","gpu","token","hyperscale"].map((v)=>({value:v,label:v}))}/><Select label="Priority *" value={priority} onChange={(e)=>setPriority(e.target.value as SubmissionPriority)} options={["low","normal","high","urgent"].map((v)=>({value:v,label:v}))}/></div>{message?<p role="alert" className="mt-4 text-xs text-ink-dim">{message}</p>:null}<button type="submit" disabled={saving} className="mt-5 rounded-full bg-accent px-5 py-2.5 text-xs font-bold uppercase tracking-wider text-accent-fg disabled:opacity-50">{saving?"Converting…":"Convert to deal"}</button></form>:null}</WorkspacePage>;
}